package com.example.ui

object BrowserTranslator {
    val TRANSLATIONS = mapOf(
        "简体中文" to mapOf(
            "Search or Enter URL" to "搜索或输入网址",
            "search" to "搜索",
            "Settings" to "设置",
            "General" to "常规",
            "GENERAL" to "常规",
            "Customization" to "个性化",
            "CUSTOMIZATION" to "个性化",
            "Languages" to "语言",
            "Active" to "当前激活",
            "Active: " to "当前激活: ",
            "Clear Browsing Data" to "清除浏览器数据",
            "History cleared successfully" to "历史记录清除成功",
            "Bookmarks" to "书签",
            "Bookmarked" to "已添加书签",
            "History" to "历史记录",
            "Blocked Trackers" to "已阻止的跟踪器",
            "Block Ads" to "屏蔽广告",
            "Ad Blocker" to "广告拦截",
            "Total Ads Blocked" to "已拦截广告数",
            "Total Trackers Blocked" to "已阻止跟踪器数",
            "New Tab" to "新标签页",
            "Tabs" to "标签页",
            "Cancel" to "取消",
            "Clear" to "清除",
            "Success" to "成功",
            "All stored website permissions have been cleared" to "所有存储的网站权限也已清除",
            "Search Engine" to "搜索引擎",
            "Private & Secure" to "私密与安全",
            "No Bookmarks saved yet." to "尚无保存的书签。",
            "No browsing history catalog logged." to "尚无浏览历史记录。",
            "Privacy" to "隐私防范",
            "PRIVACY" to "隐私防范",
            "Custom Theme Color" to "自定义主题颜色",
            "Theme Mode" to "主题模式",
            "Font Family" to "字体系列",
            "Layout Density" to "布局密度",
            "Fluid Animations" to "流畅动画",
            "Ad & Tracker Blocker" to "广告和跟踪器拦截器",
            "Total Ads & Trackers Blocked" to "已拦截的广告和跟踪器总数",
            "Emerald Green" to "祖母绿",
            "Sky Blue" to "天蓝色",
            "Sunset Orange" to "落日橙",
            "Cyber Lavender" to "网络薰衣草",
            "Obsidian Slate" to "黑曜石石板",
            "Light" to "浅色",
            "Dark" to "深色",
            "System" to "系统",
            "Sans-serif" to "无衬线体",
            "Playfair" to "Playfair 衬线",
            "Monospace" to "等宽字体",
            "Compact" to "紧凑",
            "Moderate" to "适中",
            "Comfortable" to "舒适",
            "Default" to "默认",
            "Done" to "完成",
            "OK" to "确定",
            "Close" to "关闭",
            "Open in New Tab" to "在新标签页中打开",
            "Share Link" to "分享链接",
            "Copy Link" to "复制链接",
            "Delete Bookmark" to "删除书签",
            "Delete History" to "删除历史记录",
            "Are you sure you want to clear all user history data?" to "您确定要清除所有用户历史数据吗？",
            "Are you sure you want to permanently delete all browsing logs?" to "您确定要永久删除所有浏览日志吗？",
            "Clear All History" to "清除所有历史记录",
            "Clear All" to "全部清除",
            "Delete Activity" to "删除活动",
            "Restore" to "还原",
            "Speed Dial" to "快捷访问",
            "Customize Speed Dial" to "自定义快捷访问",
            "Add Shortcut" to "添加快捷方式",
            "Shortcut Name" to "快捷方式名称",
            "Shortcut URL" to "快捷方式网址",
            "Add" to "添加",
            "Delete" to "删除",
            "Edit Shortcut" to "编辑快捷方式",
            "Save" to "保存",
            "Ad-Blocking Protection" to "广告拦截保护",
            "Stop intrusive ads and malicious popups" to "拦截侵入性广告和恶意弹窗",
            "Anti-Tracker Shield" to "反跟踪器盾牌",
            "Prevent tracking pixels from recording cookies" to "防止跟踪像素记录 Cookie",
            "Allow Website Notifications" to "允许网站通知",
            "Stay in Browser" to "留在浏览器",
            "Open App" to "打开 App",
            "Clear address text" to "清除地址文本",
            "Refresh Web Page" to "刷新网页",
            "Downloads" to "下载",
            "No downloads initiated in this session" to "此会话期间没有开始任何下载",
            "Shield inactive" to "防护未激活",
            "Total Blocked" to "已阻止总数",
            "App not installed, loading in browser" to "未安装关联应用，已在浏览器中加载",
            "Download started" to "下载已开始",
            "Download failed" to "下载失败",
            "Search or enter address" to "搜索或输入网址",
            "Search settings..." to "搜索设置...",
            "Site Permissions" to "网站权限",
            "Allow Location Access" to "允许访问位置信息",
            "Location permission active" to "位置权限已激活",
            "Allow site to ask for location" to "允许网站请求位置",
            "Allow Camera Access" to "允许访问摄像头",
            "Camera permission active" to "摄像头权限已激活",
            "Allow site to ask for camera" to "允许网站请求摄像头",
            "Allow Microphone Access" to "允许访问麦克风",
            "Microphone permission active" to "麦克风权限已激活",
            "Allow site to ask for microphone" to "允许网站请求麦克风",
            "Shield Privacy Guard" to "Shield 隐私防线",
            "ColorOS 16 Adaptive Interceptor • Running securely" to "ColorOS 16 自适应拦截器 • 安全运行中",
            "Session Blocked" to "本会话已拦截",
            "English (US)" to "美式英语",
            "简体中文" to "简体中文",
            "Español" to "西班牙语",
            "Deutsch" to "德语",
            "Français" to "法语",
            "All" to "全部",
            "Ongoing" to "进行中",
            "Complete" to "已完成",
            "1.2 GB • Completed" to "1.2 GB • 已完成",
            "Downloading..." to "下载中...",
            "4.8 MB • Yesterday" to "4.8 MB • 昨天",
            "850 KB • May 20" to "850 KB • 5月20日",
            "Search downloads" to "搜索下载内容",
            "Shield Privacy Guard" to "Shield 隐私防线",
            "Browser Settings" to "浏览器设置",
            "Menu" to "菜单",
            "Light Mode" to "浅色模式",
            "Dark Mode" to "深色模式",
            "Blocked" to "拦截了",
            "trackers" to "个跟踪器",
            "Welcome to Search" to "欢迎来到搜索",
            "Experience the web with fluid elegance\nand uncompromising privacy." to "以流畅的优雅和毫不妥协的隐私\n体验真正的网络。",
            "Skip" to "跳过",
            "Launch Search" to "启动搜索",
            "Continue" to "继续",
            "Select your preferred language for searches and interface." to "选择您进行搜索和界面的首选语言。",
            "Search languages..." to "搜索语言...",
            "Choose the default service used when typing queries in the address bar." to "选择在地址栏中键入查询时使用的默认服务。"
        ),
        "Español" to mapOf(
            "Search or Enter URL" to "Buscar o ingresar URL",
            "search" to "búsqueda",
            "Settings" to "Ajustes",
            "General" to "General",
            "GENERAL" to "GENERAL",
            "Customization" to "Personalización",
            "CUSTOMIZATION" to "PERSONALIZACIÓN",
            "Languages" to "Idiomas",
            "Active" to "Activo",
            "Active: " to "Activo: ",
            "Clear Browsing Data" to "Borrar datos de navegación",
            "History cleared successfully" to "Historial borrado con éxito",
            "Bookmarks" to "Marcadores",
            "Bookmarked" to "Marcado",
            "History" to "Historial",
            "Blocked Trackers" to "Rastreadores bloqueados",
            "Block Ads" to "Bloquear anuncios",
            "Ad Blocker" to "Bloqueador de anuncios",
            "Total Ads Blocked" to "Anuncios bloqueados",
            "Total Trackers Blocked" to "Rastreadores bloqueados",
            "New Tab" to "Nueva pestaña",
            "Tabs" to "Pestañas",
            "Cancel" to "Cancelar",
            "Clear" to "Borrar",
            "Success" to "Éxito",
            "All stored website permissions have been cleared" to "Todos los permisos almacenados de sitios de red han sido borrados",
            "Search Engine" to "Motor de búsqueda",
            "Private & Secure" to "Privado y seguro",
            "No Bookmarks saved yet." to "No hay marcadores guardados aún.",
            "No browsing history catalog logged." to "No se ha registrado historial de navegación.",
            "Privacy" to "Privacidad",
            "PRIVACY" to "PRIVACIDAD",
            "Custom Theme Color" to "Color de tema personalizado",
            "Theme Mode" to "Modo de tema",
            "Font Family" to "Familia de fuentes",
            "Layout Density" to "Densidad de diseño",
            "Fluid Animations" to "Animaciones fluidas",
            "Ad & Tracker Blocker" to "Bloqueador de anuncios y rastreadores",
            "Total Ads & Trackers Blocked" to "Total de anuncios y rastreadores bloqueados",
            "Emerald Green" to "Verde esmeralda",
            "Sky Blue" to "Azul cielo",
            "Sunset Orange" to "Naranja atardecer",
            "Cyber Lavender" to "Ciberlavanda",
            "Obsidian Slate" to "Pizarra obsidiana",
            "Light" to "Claro",
            "Dark" to "Oscuro",
            "System" to "Sistema",
            "Sans-serif" to "Sans-serif",
            "Playfair" to "Playfair",
            "Monospace" to "Monospace",
            "Compact" to "Compacto",
            "Moderate" to "Moderado",
            "Comfortable" to "Cómodo",
            "Default" to "Por defecto",
            "Done" to "Hecho",
            "OK" to "OK",
            "Close" to "Cerrar",
            "Open in New Tab" to "Abrir en nueva pestaña",
            "Share Link" to "Compartir enlace",
            "Copy Link" to "Copiar enlace",
            "Delete Bookmark" to "Eliminar marcador",
            "Delete History" to "Eliminar historial",
            "Are you sure you want to clear all user history data?" to "¿Está seguro de que desea borrar todos los datos de historial del usuario?",
            "Are you sure you want to permanently delete all browsing logs?" to "¿Está seguro de que desea eliminar permanentemente todos los registros de navegación?",
            "Clear All History" to "Borrar todo el historial",
            "Clear All" to "Borrar todo",
            "Delete Activity" to "Eliminar actividad",
            "Restore" to "Restaurar",
            "Speed Dial" to "Marcado rápido",
            "Customize Speed Dial" to "Personalizar marcado rápido",
            "Add Shortcut" to "Añadir acceso directo",
            "Shortcut Name" to "Nombre del acceso directo",
            "Shortcut URL" to "URL del acceso directo",
            "Add" to "Añadir",
            "Delete" to "Eliminar",
            "Edit Shortcut" to "Editar acceso directo",
            "Save" to "Guardar",
            "Ad-Blocking Protection" to "Protección de bloqueo de anuncios",
            "Stop intrusive ads and malicious popups" to "Detener anuncios invasivos y popups maliciosos",
            "Anti-Tracker Shield" to "Escudo anti-rastreo",
            "Prevent tracking pixels from recording cookies" to "Evitar que los píxeles de seguimiento registren cookies",
            "Allow Website Notifications" to "Permitir notificaciones de sitios",
            "Stay in Browser" to "Permanecer en el navegador",
            "Open App" to "Abrir App",
            "Clear address text" to "Borrar texto de dirección",
            "Refresh Web Page" to "Actualizar página",
            "Downloads" to "Descargas",
            "No downloads initiated in this session" to "No se han iniciado descargas en esta sesión",
            "Shield inactive" to "Escudo inactivo",
            "Total Blocked" to "Total bloqueados",
            "App not installed, loading in browser" to "Aplicación no instalada, abriendo en el navegador",
            "Download started" to "Descarga iniciada",
            "Download failed" to "Descarga fallida",
            "Search or enter address" to "Buscar o ingresar URL",
            "Search settings..." to "Buscar en ajustes...",
            "Site Permissions" to "Permisos de sitio",
            "Allow Location Access" to "Permitir acceso a ubicación",
            "Location permission active" to "Permiso de ubicación activo",
            "Allow site to ask for location" to "Permitir al sitio pedir ubicación",
            "Allow Camera Access" to "Permitir acceso a cámara",
            "Camera permission active" to "Permiso de cámara activo",
            "Allow site to ask for camera" to "Permitir al sitio pedir cámara",
            "Allow Microphone Access" to "Permitir acceso a micrófono",
            "Microphone permission active" to "Permiso de micrófono activo",
            "Allow site to ask for microphone" to "Permitir al sitio pedir micrófono",
            "Shield Privacy Guard" to "Escudo Protector de Privacidad",
            "ColorOS 16 Adaptive Interceptor • Running securely" to "Interceptor adaptativo ColorOS 16 • Ejecutando de forma segura",
            "Session Blocked" to "Bloqueados en la sesión",
            "English (US)" to "Inglés (EE. UU.)",
            "简体中文" to "Chino simplificado",
            "Español" to "Español",
            "Deutsch" to "Alemán",
            "Français" to "Francés",
            "All" to "Todo",
            "Ongoing" to "En curso",
            "Complete" to "Completado",
            "1.2 GB • Completed" to "1.2 GB • Completado",
            "Downloading..." to "Descargando...",
            "4.8 MB • Yesterday" to "4.8 MB • Ayer",
            "850 KB • May 20" to "850 KB • 20 de mayo",
            "Search downloads" to "Buscar descargas",
            "Shield Privacy Guard" to "Escudo de Privacidad",
            "Browser Settings" to "Configuración del navegador",
            "Menu" to "Menú",
            "Light Mode" to "Modo claro",
            "Dark Mode" to "Modo oscuro",
            "Blocked" to "Bloqueados",
            "trackers" to "rastreadores",
            "Welcome to Search" to "Bienvenido a Search",
            "Experience the web with fluid elegance\nand uncompromising privacy." to "Experimenta la web con elegancia fluida\ny privacidad sin concesiones.",
            "Skip" to "Saltar",
            "Launch Search" to "Lanzar Búsqueda",
            "Continue" to "Continuar",
            "Select your preferred language for searches and interface." to "Selecciona tu idioma preferido para búsquedas e interfaz.",
            "Search languages..." to "Buscar idiomas...",
            "Choose the default service used when typing queries in the address bar." to "Elige el servicio predeterminado utilizado al escribir consultas en la barra de direcciones."
        ),
        "Deutsch" to mapOf(
            "Search or Enter URL" to "Suchen oder URL eingeben",
            "search" to "Suche",
            "Settings" to "Einstellungen",
            "General" to "Allgemein",
            "GENERAL" to "ALLGEMEIN",
            "Customization" to "Personalisierung",
            "CUSTOMIZATION" to "PERSONALISIERUNG",
            "Languages" to "Sprachen",
            "Active" to "Aktiv",
            "Active: " to "Aktiv: ",
            "Clear Browsing Data" to "Browserdaten löschen",
            "History cleared successfully" to "Verlauf erfolgreich gelöscht",
            "Bookmarks" to "Lesezeichen",
            "Bookmarked" to "Als Lesezeichen gespeichert",
            "History" to "Verlauf",
            "Blocked Trackers" to "Blockierte Tracker",
            "Block Ads" to "Werbung blockieren",
            "Ad Blocker" to "Werbeblocker",
            "Total Ads Blocked" to "Werbung blockiert",
            "Total Trackers Blocked" to "Tracker blockiert",
            "New Tab" to "Neuer Tab",
            "Tabs" to "Tabs",
            "Cancel" to "Abbrechen",
            "Clear" to "Löschen",
            "Success" to "Erfolg",
            "All stored website permissions have been cleared" to "Alle gespeicherten Website-Berechtigungen wurden gelöscht",
            "Search Engine" to "Suchmaschine",
            "Private & Secure" to "Privat & Sicher",
            "No Bookmarks saved yet." to "Noch keine Lesezeichen gespeichert.",
            "No browsing history catalog logged." to "Kein Browserverlauf protokolliert.",
            "Privacy" to "Privatsphäre",
            "PRIVACY" to "PRIVATSPHÄRE",
            "Custom Theme Color" to "Benutzerdefinierte Designfarbe",
            "Theme Mode" to "Design-Modus",
            "Font Family" to "Schriftart",
            "Layout Density" to "Layout-Dichte",
            "Fluid Animations" to "Flüssige Animationen",
            "Ad & Tracker Blocker" to "Werbe- & Tracker-Blocker",
            "Total Ads & Trackers Blocked" to "Werbung & Tracker insgesamt blockiert",
            "Emerald Green" to "Smaragdgrün",
            "Sky Blue" to "Himmelblau",
            "Sunset Orange" to "Sonnenuntergangsorange",
            "Cyber Lavender" to "Cyber-Lavendel",
            "Obsidian Slate" to "Obsidianschiefer",
            "Light" to "Hell",
            "Dark" to "Dunkel",
            "System" to "System",
            "Sans-serif" to "Sans-Serif",
            "Playfair" to "Playfair",
            "Monospace" to "Monospace",
            "Compact" to "Kompakt",
            "Moderate" to "Moderat",
            "Comfortable" to "Komfortabel",
            "Default" to "Standard",
            "Done" to "Fertig",
            "OK" to "OK",
            "Close" to "Schließen",
            "Open in New Tab" to "In neuem Tab öffnen",
            "Share Link" to "Link teilen",
            "Copy Link" to "Link kopieren",
            "Delete Bookmark" to "Lesezeichen löschen",
            "Delete History" to "Verlauf löschen",
            "Are you sure you want to clear all user history data?" to "Möchten Sie wirklich alle Benutzerverlaufsdaten löschen?",
            "Are you sure you want to permanently delete all browsing logs?" to "Möchten Sie wirklich alle Browserprotokolle dauerhaft löschen?",
            "Clear All History" to "Ganzen Verlauf löschen",
            "Clear All" to "Alles löschen",
            "Delete Activity" to "Aktivität löschen",
            "Restore" to "Wiederherstellen",
            "Speed Dial" to "Kurzwahl",
            "Customize Speed Dial" to "Kurzwahl anpassen",
            "Add Shortcut" to "Verknüpfung hinzufügen",
            "Shortcut Name" to "Name der Verknüpfung",
            "Shortcut URL" to "URL der Verknüpfung",
            "Add" to "Hinzufügen",
            "Delete" to "Löschen",
            "Edit Shortcut" to "Verknüpfung bearbeiten",
            "Save" to "Speichern",
            "Ad-Blocking Protection" to "Werbeblocker-Schutz",
            "Stop intrusive ads and malicious popups" to "Invasive Werbung und schädliche Popups stoppen",
            "Anti-Tracker Shield" to "Anti-Tracker-Schutzschild",
            "Prevent tracking pixels from recording cookies" to "Verhindern, dass Tracking-Pixel Cookies aufzeichnen",
            "Allow Website Notifications" to "Website-Benachrichtigungen zulassen",
            "Stay in Browser" to "Im Browser bleiben",
            "Open App" to "App öffnen",
            "Clear address text" to "Adressfeld leeren",
            "Refresh Web Page" to "Seite aktualisieren",
            "Downloads" to "Downloads",
            "No downloads initiated in this session" to "In dieser Sitzung wurden keine Downloads gestartet",
            "Shield inactive" to "Schutz inaktiv",
            "Total Blocked" to "Insgesamt blockiert",
            "App not installed, loading in browser" to "App nicht installiert, wird im Browser geladen",
            "Download started" to "Download gestartet",
            "Download failed" to "Download fehlgeschlagen",
            "Search or enter address" to "Suchen oder Adresse eingeben",
            "Search settings..." to "Einstellungen suchen...",
            "Site Permissions" to "Website-Berechtigungen",
            "Allow Location Access" to "Standortzugriff erlauben",
            "Location permission active" to "Standortberechtigung aktiv",
            "Allow site to ask for location" to "Website nach Standort fragen lassen",
            "Allow Camera Access" to "Kamerazugriff erlauben",
            "Camera permission active" to "Kameraberechtigung aktiv",
            "Allow site to ask for camera" to "Website nach Kamera fragen lassen",
            "Allow Microphone Access" to "Mikrofonzugriff erlauben",
            "Microphone permission active" to "Mikrofonberechtigung aktiv",
            "Allow site to ask for microphone" to "Website nach Mikrofon fragen lassen",
            "Shield Privacy Guard" to "Schild Privatsphäre-Schutz",
            "ColorOS 16 Adaptive Interceptor • Running securely" to "ColorOS 16 Adaptiver Abfänger • Läuft sicher",
            "Session Blocked" to "In dieser Sitzung blockiert",
            "English (US)" to "Englisch (USA)",
            "简体中文" to "Vereinfachtes Chinesisch",
            "Español" to "Spanisch",
            "Deutsch" to "Deutsch",
            "Français" to "Französisch",
            "All" to "Alle",
            "Ongoing" to "Laufend",
            "Complete" to "Abgeschlossen",
            "1.2 GB • Completed" to "1.2 GB • Abgeschlossen",
            "Downloading..." to "Wird heruntergeladen...",
            "4.8 MB • Yesterday" to "4.8 MB • Gestern",
            "850 KB • May 20" to "850 KB • 20. Mai",
            "Search downloads" to "Downloads suchen",
            "Shield Privacy Guard" to "Schild Privatsphäre-Schutz",
            "Browser Settings" to "Browser-Einstellungen",
            "Menu" to "Menü",
            "Light Mode" to "Heller Modus",
            "Dark Mode" to "Dunkler Modus",
            "Blocked" to "Blockiert",
            "trackers" to "Tracker",
            "Welcome to Search" to "Willkommen bei Search",
            "Experience the web with fluid elegance\nand uncompromising privacy." to "Erlebe das Web mit fließender Eleganz\nund kompromissloser Privatsphäre.",
            "Skip" to "Überspringen",
            "Launch Search" to "Suche starten",
            "Continue" to "Weiter",
            "Select your preferred language for searches and interface." to "Wähle deine bevorzugte Sprache für die Suche und Benutzeroberfläche aus.",
            "Search languages..." to "Sprachen durchsuchen...",
            "Choose the default service used when typing queries in the address bar." to "Wähle den Standarddienst, der bei der Eingabe von Suchanfragen in die Adressleiste verwendet wird."
        ),
        "Français" to mapOf(
            "Search or Enter URL" to "Rechercher ou saisir une URL",
            "search" to "recherche",
            "Settings" to "Paramètres",
            "General" to "Général",
            "GENERAL" to "GÉNÉRAL",
            "Customization" to "Personnalisation",
            "CUSTOMIZATION" to "PERSONNALISATION",
            "Languages" to "Langues",
            "Active" to "Actif",
            "Active: " to "Actif: ",
            "Clear Browsing Data" to "Effacer les données de navigation",
            "History cleared successfully" to "Historique effacé avec succès",
            "Bookmarks" to "Signets",
            "Bookmarked" to "Ajouté aux signets",
            "History" to "Historique",
            "Blocked Trackers" to "Traqueurs bloqués",
            "Block Ads" to "Bloquer les publicités",
            "Ad Blocker" to "Bloqueur de pub",
            "Total Ads Blocked" to "Publicités bloquées",
            "Total Trackers Blocked" to "Traqueurs bloqués",
            "New Tab" to "Nouvel onglet",
            "Tabs" to "Onglets",
            "Cancel" to "Annuler",
            "Clear" to "Effacer",
            "Success" to "Succès",
            "All stored website permissions have been cleared" to "Toutes les autorisations de sites stockées ont été effacées",
            "Search Engine" to "Moteur de recherche",
            "Private & Secure" to "Privé et sécurisé",
            "No Bookmarks saved yet." to "Aucun signet enregistré pour le moment.",
            "No browsing history catalog logged." to "Aucun historique de navigation enregistré.",
            "Privacy" to "Confidentialité",
            "PRIVACY" to "CONFIDENTIALITÉ",
            "Custom Theme Color" to "Couleur de thème personnalisée",
            "Theme Mode" to "Mode de thème",
            "Font Family" to "Famille de polices",
            "Layout Density" to "Densité de mise en page",
            "Fluid Animations" to "Animations fluides",
            "Ad & Tracker Blocker" to "Bloqueur de pubs et traqueurs",
            "Total Ads & Trackers Blocked" to "Total de publicités et traqueurs bloqués",
            "Emerald Green" to "Vert émeraude",
            "Sky Blue" to "Bleu ciel",
            "Sunset Orange" to "Couché de soleil orange",
            "Cyber Lavender" to "Cyber lavande",
            "Obsidian Slate" to "Ardoise obsidienne",
            "Light" to "Clair",
            "Dark" to "Sombre",
            "System" to "Système",
            "Sans-serif" to "Sans-serif",
            "Playfair" to "Playfair",
            "Monospace" to "Monospace",
            "Compact" to "Compact",
            "Moderate" to "Modéré",
            "Comfortable" to "Confortable",
            "Default" to "Par défaut",
            "Done" to "Terminé",
            "OK" to "OK",
            "Close" to "Fermer",
            "Open in New Tab" to "Ouvrir dans un nouvel onglet",
            "Share Link" to "Partager le lien",
            "Copy Link" to "Copier le lien",
            "Delete Bookmark" to "Supprimer le signet",
            "Delete History" to "Supprimer l'historique",
            "Are you sure you want to clear all user history data?" to "Êtes-vous sûr de vouloir effacer toutes les données d'historique de l'utilisateur ?",
            "Are you sure you want to permanently delete all browsing logs?" to "Êtes-vous sûr de vouloir supprimer définitivement tous les journaux de navigation ?",
            "Clear All History" to "Effacer tout l'historique",
            "Clear All" to "Tout effacer",
            "Delete Activity" to "Supprimer l'activité",
            "Restore" to "Restaurer",
            "Speed Dial" to "Numérotation rapide",
            "Customize Speed Dial" to "Personnaliser la numérotation rapide",
            "Add Shortcut" to "Ajouter un raccourci",
            "Shortcut Name" to "Nom du raccourci",
            "Shortcut URL" to "URL du raccourci",
            "Add" to "Ajouter",
            "Delete" to "Supprimer",
            "Edit Shortcut" to "Modifier le raccourci",
            "Save" to "Enregistrer",
            "Ad-Blocking Protection" to "Protection anti-pub",
            "Stop intrusive ads and malicious popups" to "Bloquer les publicités intrusives et popups malicieux",
            "Anti-Tracker Shield" to "Bouclier anti-traquage",
            "Prevent tracking pixels from recording cookies" to "Empêcher les pixels invisibles d'enregistrer des cookies",
            "Allow Website Notifications" to "Autoriser les notifications de sites",
            "Stay in Browser" to "Rester sur le navigateur",
            "Open App" to "Ouvrir l'App",
            "Clear address text" to "Effacer le texte de l'adresse",
            "Refresh Web Page" to "Rafraîchir la page",
            "Downloads" to "Téléchargements",
            "No downloads initiated in this session" to "Aucun téléchargement démarré dans cette session",
            "Shield inactive" to "Bouclier inactif",
            "Total Blocked" to "Total bloqué",
            "App not installed, loading in browser" to "App non installée, chargement sur le navigateur",
            "Download started" to "Téléchargement démarré",
            "Download failed" to "Téléchargement échoué",
            "Search or enter address" to "Rechercher ou saisir une adresse",
            "Search settings..." to "Rechercher des paramètres...",
            "Site Permissions" to "Autorisations du site",
            "Allow Location Access" to "Autoriser l'accès à la position",
            "Location permission active" to "Autorisation de position active",
            "Allow site to ask for location" to "Autoriser le site à demander la position",
            "Allow Camera Access" to "Autoriser l'accès à l'appareil photo",
            "Camera permission active" to "Autorisation de l'appareil photo active",
            "Allow site to ask for camera" to "Autoriser le site à demander l'appareil photo",
            "Allow Microphone Access" to "Autoriser l'accès au micro",
            "Microphone permission active" to "Autorisation du micro active",
            "Allow site to ask for microphone" to "Autoriser le site à demander le micro",
            "Shield Privacy Guard" to "Bouclier de protection de la vie privée",
            "ColorOS 16 Adaptive Interceptor • Running securely" to "Intercepteur adaptatif ColorOS 16 • Fonctionne en toute sécurité",
            "Session Blocked" to "Bloqué cette session",
            "English (US)" to "Anglais (États-Unis)",
            "简体中文" to "Chinois simplifié",
            "Español" to "Espagnol",
            "Deutsch" to "Allemand",
            "Français" to "Français",
            "All" to "Tout",
            "Ongoing" to "En cours",
            "Complete" to "Terminé",
            "1.2 GB • Completed" to "1.2 Go • Terminé",
            "Downloading..." to "Téléchargement...",
            "4.8 MB • Yesterday" to "4.8 Mo • Hier",
            "850 KB • May 20" to "850 Ko • 20 Mai",
            "Search downloads" to "Rechercher des téléchargements",
            "Shield Privacy Guard" to "Bouclier de confidentialité",
            "Browser Settings" to "Paramètres du navigateur",
            "Menu" to "Menu",
            "Light Mode" to "Mode clair",
            "Dark Mode" to "Mode sombre",
            "Blocked" to "Bloqué",
            "trackers" to "traqueurs",
            "Welcome to Search" to "Bienvenue sur Search",
            "Experience the web with fluid elegance\nand uncompromising privacy." to "Expérimentez le web avec une élégance fluide\net une confidentialité sans compromis.",
            "Skip" to "Ignorer",
            "Launch Search" to "Lancer la recherche",
            "Continue" to "Continuer",
            "Select your preferred language for searches and interface." to "Sélectionnez votre langue de préférence pour les recherches et l'interface.",
            "Search languages..." to "Rechercher des langues...",
            "Choose the default service used when typing queries in the address bar." to "Choisissez le service par défaut utilisé lors de la saisie de requêtes dans la barre d'adresses."
        )
    )

    fun translateText(text: String, lang: String): String {
        if (lang == "English (US)") return text
        val trimText = text.trim()
        val hasColon = trimText.endsWith(":")
        val lookupKey = if (hasColon) trimText.substring(0, trimText.length - 1).trim() else trimText

        // Handle dynamic string Active state
        if (trimText.startsWith("Active: ")) {
            val value = trimText.removePrefix("Active: ")
            val translatedValue = translateText(value, lang)
            val prefix = if (lang == "简体中文") "当前" else if (lang == "Español") "Activo" else if (lang == "Deutsch") "Aktiv" else if (lang == "Français") "Actif" else "Active"
            return "$prefix: $translatedValue"
        }

        // Handle dynamic ad block text
        if (trimText.startsWith("Blocked ") && trimText.contains("this session")) {
            val parts = trimText.split(" ")
            val sessionCount = parts.getOrNull(1) ?: "0"
            val totalCount = trimText.substringAfter("Total: ").substringBefore(")")
            return when (lang) {
                "简体中文" -> "本会话已阻止 $sessionCount 个广告 (总计: $totalCount)"
                "Español" -> "Anuncios bloqueados en esta sesión: $sessionCount (Total: $totalCount)"
                "Deutsch" -> "$sessionCount Anzeigen in dieser Sitzung blockiert (Gesamt: $totalCount)"
                "Français" -> "$sessionCount publicités bloquées cette session (Total: $totalCount)"
                else -> text
            }
        }

        // Handle dynamic tracker block text
        if (trimText.startsWith("Blocked ") && trimText.contains("cookies/trackers")) {
            val parts = trimText.split(" ")
            val sessionCount = parts.getOrNull(1) ?: "0"
            val totalCount = trimText.substringAfter("Total: ").substringBefore(")")
            return when (lang) {
                "简体中文" -> "本会话已阻止 $sessionCount 个跟踪器/Cookie (总计: $totalCount)"
                "Español" -> "Rastreadores/cookies bloqueados en esta sesión: $sessionCount (Total: $totalCount)"
                "Deutsch" -> "$sessionCount Tracker/Cookies in dieser Sitzung blockiert (Gesamt: $totalCount)"
                "Français" -> "$sessionCount traqueurs/cookies bloqués cette session (Total: $totalCount)"
                else -> text
            }
        }

        // Handle download started
        if (trimText.startsWith("Download started:")) {
            val fileName = trimText.substringAfter("Download started: ")
            val prefix = when (lang) {
                "简体中文" -> "下载已开始"
                "Español" -> "Descarga iniciada"
                "Deutsch" -> "Download gestartet"
                "Français" -> "Téléchargement démarré"
                else -> "Download started"
            }
            return "$prefix: $fileName"
        }

        // Handle download failed
        if (trimText.startsWith("Download failed:")) {
            val error = trimText.substringAfter("Download failed: ")
            val prefix = when (lang) {
                "简体中文" -> "下载失败"
                "Español" -> "Descarga fallida"
                "Deutsch" -> "Download fehlgeschlagen"
                "Français" -> "Téléchargement échoué"
                else -> "Download failed"
            }
            return "$prefix: $error"
        }

        val translated = TRANSLATIONS[lang]?.get(lookupKey)
        if (translated != null) {
            return if (hasColon) "$translated:" else translated
        }

        // Fallback search with case-insensitive matcher
        val map = TRANSLATIONS[lang] ?: return text
        for ((key, value) in map) {
            if (key.equals(lookupKey, ignoreCase = true)) {
                return if (hasColon) "$value:" else value
            }
        }

        return text
    }
}
