name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo $ENCODED_KEYSTORE | base64 -d > my-upload-key.jks

      - name: Build Release APK
        env:
          KEYSTORE_PATH: my-upload-key.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: |
          VERSION_NAME=${GITHUB_REF#refs/tags/v}
          if [ "$VERSION_NAME" = "${GITHUB_REF}" ]; then
            mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/BrowserApp-release.apk
          else
            mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/BrowserApp-v${VERSION_NAME}-release.apk
          fi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk

      - name: Generate SHA-256
        id: shasum
        run: |
          VERSION_NAME=${GITHUB_REF#refs/tags/v}
          if [ "$VERSION_NAME" = "${GITHUB_REF}" ]; then
            SHA256=$(sha256sum app/build/outputs/apk/release/BrowserApp-release.apk | awk '{ print $1 }')
          else
            SHA256=$(sha256sum app/build/outputs/apk/release/BrowserApp-v${VERSION_NAME}-release.apk | awk '{ print $1 }')
          fi
          echo "SHA256: $SHA256" > release-notes.txt
          echo "Added new features and bug fixes." >> release-notes.txt

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/BrowserApp-v*-release.apk
          body_path: release-notes.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
